/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MarketsImport } from './routes/markets'
import { Route as BookmarksImport } from './routes/bookmarks'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MarketsRoute = MarketsImport.update({
  path: '/markets',
  getParentRoute: () => rootRoute,
} as any)

const BookmarksRoute = BookmarksImport.update({
  path: '/bookmarks',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bookmarks': {
      preLoaderRoute: typeof BookmarksImport
      parentRoute: typeof rootRoute
    }
    '/markets': {
      preLoaderRoute: typeof MarketsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BookmarksRoute,
  MarketsRoute,
])

/* prettier-ignore-end */
